New lazer structure
L-Mario564/osu.js pull request #15
Opened 2024-03-02 15:52 UTC by YoruNoKen

This pull request updates the library to the api version after lazer's pp release.

2024-04-02 19:25 UTC, L-Mario564 requested changes
I see a lot of breaking changes here, I think it would be best to have the user be able to specify the `x-api-version` header specifically in the endpoints in which they can be applied and then map out the return types as needed.

2024-04-02 19:28 UTC, YoruNoKen commented
> I see a lot of breaking changes here, I think it would be best to have the user be able to specify the `x-api-version` header specifically in the endpoints in which they can be applied and then map out the return types as needed.

so, an enum you would pass in the `Client` class while initializing the client?
```ts
const client = new Client(accessToken, ApiVersion.Lazer);
```
enum name would be subject to change.

2024-04-09 09:19 UTC, YoruNoKen commented
dude, I just accidently deleted the branch

2024-04-09 10:21 UTC, YoruNoKen commented
I named the old types to have `Legacy` at the start, let me know if I should put anything else.

2024-04-09 16:11 UTC, yorunoken commented
@L-Mario564
> I see a lot of breaking changes here, I think it would be best to have the user be able to specify the x-api-version header specifically in the endpoints in which they can be applied and then map out the return types as needed.

I've adressed the breaking changes. It now automatically returns the old structure **unless** you pass in `true` after required parameters.

2025-03-28 17:36 UTC, L-Mario564 commented
@yorunoken Hey there, appreciate your efforts, although I've now implemented the new `x-api-header` functionality in a different way that would allow me to maintain the project easier. This is now available in latest.

2025-03-28 17:36 UTC, closed without merging